### ISSUE TITLE
not working on eslint: "^4.16.0"

### ISSUE THREAD

**Issue by marcelmokos** [erikdesjardins/eslint-plugin-dollar-sign#11]
Error: Failed to load plugin dollar-sign: Cannot find module 'eslint-plugin-dollar-sign'

.eslint.yml

```yml
---
extends:
  - airbnb-base/legacy
  - prettier

env:
  amd: true
  browser: true
  jasmine: true
  jquery: true
  es6: false

parserOptions:
  ecmaVersion: 5
  ecmaFeatures:
    globalReturn: false

plugins:
  - import
  - prettier
  - dollar-sign

rules:
  dollar-sign/dollar-sign:
    - error
    - ignoreProperties
```

**Comment by erikdesjardins** [comment]
What does `npm ls eslint-plugin-dollar-sign` output?

**Comment by marcelmokos** [comment]
I am sure that did `npm i --save-dev eslint-plugin-dollar-sign` and I did check the `node_modules` and everything seemed fine.
 
```
npm ls eslint-plugin-dollar-sign
project
└── eslint-plugin-dollar-sign@1.0.1 
```

**Comment by erikdesjardins** [comment]
With that out of the way, I can't debug any further without an example repo.

**Comment by marcelmokos** [comment]
I found the problem, It was caused by setting in IDE the eslint was taken from another directory and It caused the issue in that directory node_modules were missing eslint-plugin-dollar-sign. Cannot find module 'eslint-plugin-dollar-sign' you can close the issue.

**Comment by diegocr** [comment]
@erikdesjardins is this plugin abandoned? it was kinda handy :)

Perhaps you can talk with @4dvn-hieu about his [fork](https://github.com/4dvn-hieu/eslint-plugin-dollar-sign) since he seems to have [fixed](https://github.com/4dvn-hieu/eslint-plugin-dollar-sign/commit/09702aa6592725d89834ecaa288740558f677a2f) it for ESLint 8+
